postgres_url: postgres://YourUserName:YourPassword@YourHost:5432/YourDatabase?sslmode=disable
redis_url: redis://127.0.0.1:6379/0
web3_url: https://mainnet.infura.io
web3_ws: wss://mainnet.infura.io/ws
ethplorer_apikey: freekey
resource_path: resource