sudo: required
language: bash

stages:
  - build

jobs:
  include:
    - stage: build
      services:
        - docker
      script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t wlchn/hydroscan-api .
          - docker push wlchn/hydroscan-api