stages:
  - build

build:
  language: bash
  services:
    - docker
  stage: build
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t wlchn/hydroscan-api .
    - docker push wlchn/hydroscan-api
